name = "blog"
type = "webpack"
account_id = "c061f1cd2f49dcccce2a820601e6bac2"
workers_dev = false
route = "blog.monsterx.cn/*"
zone_id = "6a6d6258e7306f925fe8ea1e5744d419"

[site]
bucket = "./dist"
entry-point = "workers-site"
